/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PantriesImport } from './routes/pantries'
import { Route as HelpImport } from './routes/help'
import { Route as ExplorerImport } from './routes/explorer'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PantriesRoute = PantriesImport.update({
  id: '/pantries',
  path: '/pantries',
  getParentRoute: () => rootRoute,
} as any)

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const ExplorerRoute = ExplorerImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/pantries': {
      id: '/pantries'
      path: '/pantries'
      fullPath: '/pantries'
      preLoaderRoute: typeof PantriesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explorer': typeof ExplorerRoute
  '/help': typeof HelpRoute
  '/pantries': typeof PantriesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explorer': typeof ExplorerRoute
  '/help': typeof HelpRoute
  '/pantries': typeof PantriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explorer': typeof ExplorerRoute
  '/help': typeof HelpRoute
  '/pantries': typeof PantriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/explorer' | '/help' | '/pantries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/explorer' | '/help' | '/pantries'
  id: '__root__' | '/' | '/about' | '/explorer' | '/help' | '/pantries'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExplorerRoute: typeof ExplorerRoute
  HelpRoute: typeof HelpRoute
  PantriesRoute: typeof PantriesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExplorerRoute: ExplorerRoute,
  HelpRoute: HelpRoute,
  PantriesRoute: PantriesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/explorer",
        "/help",
        "/pantries"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/explorer": {
      "filePath": "explorer.tsx"
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/pantries": {
      "filePath": "pantries.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
